### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [ioBroker/ioBroker.admin#1016]
Might be 'works as designed' but I find it extremely annoying that text in the admin UI is automatically translated to the language set in the admin settings.
For example Language set to German.
Adapter name in the list 'Heizungsregelung'. Object in the object tree: Heatingcontrol, Instance name: Heatingcontrol

This is also the case for the readme.md. The automated translation is in many cases hardly readable. Just saw one with a requirement for Knoten > 8

Especially for the readme.md etc I'd prefer to see the original language. If I want to translate I can paste it manually into  deepl or whatever.
Alternatively implement a mechanism which allows to suppress automatic translation for specific languages.

**Comment by GermanBluefox** [comment]
If you mean README.md, you can place the text, that should not be translated in quotes: \`THIS TEXT WILL NOT BE TRANSLATED\`

**Comment by macpo** [comment]
The version comments are also translated with the 5.3.1 which are really hard to read:

* The translated version in German
![image](https://user-images.githubusercontent.com/17279799/156849464-176ccf82-2549-41fa-bc79-e12f25c42f35.png)
* The original version in Englsh
![image](https://user-images.githubusercontent.com/17279799/156849530-91fb09bf-8ff1-43d3-a8e9-a07d9ecfc30e.png)

What about an option to disable the automatic translation in Readme and the changelog?

**Comment by ldittmar81** [comment]
fix Redis Config is not better. It should be "Redis configuration fixed", then we would get a better automated translation.

**Comment by Apollon77** [comment]
ALternatively simply adjust Admin language to english :-) but yes ... not ideal translation

**Comment by macpo** [comment]
I agree that the selected example is not the best. The automated translation is even worse for readme sometimes. Most of the times I want to read the original wording why I suggested the option to deactivate the automated translation for the changelog and the readme. In the readme I have the option to see the original wording in the changelog not.

**Comment by macpo** [comment]
Just another example of the admin changelog. I do not understand for example "Chips zur JSON-Konfiguration hinzugefügt"

![image](https://user-images.githubusercontent.com/17279799/167563877-d702fc21-9bd3-4796-bea4-b29a4e508b5a.png)

**Comment by jens-maus** [comment]
Sorry, but I have to join this discussion here. After months of using ioBroker.admin I also find it totally disturbing that the ChangeLog of adapter updates are displayed with their automatic translation. See, e.g. this awkward translation failure example:

![Bildschirmfoto 2022-06-09 um 10 23 17](https://user-images.githubusercontent.com/5887769/172801206-e4c9eed7-9061-4750-b1a5-fdc95a5482a2.png)

Reading `Knoten-unifi` instead of `node-unifi` really makes me puke :)

So can we please settle here for a change which:

1. either disables the translated display in ioBroker.admin in the adapter ChangeLog view alltogether, meaning that we make an exception here that the ChangeLog will *always* be displayed in english language!
2. or add an additional option to the Iobroker.admin settings where you can select the language, that one can separately select the desired language just for the Adapter ChangeLog display.

Please note, that I don't argue in principle on the automatic translation even if this is already quite questionable in itself because these automatic translations are really really bad in most cases. I am just arguing about this special case that the Adapter ChangeLog window is showing the translated text rather than just showing the english text in which 99% of the adapter developers are  actually writing their changelog.

So please! Relief us from this currently bad situation in either considering point (1) or point (2) above!

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/174648898-6b6150ac-7693-4642-8127-1a4839843adc.png)

**Comment by jens-maus** [comment]
Great! Thx @GermanBluefox

However, is this a permanent setting then or do I have to click on this each time, which I guess is what you have implemented..

**Comment by GermanBluefox** [comment]
It is permanent

**Comment by Feuer-sturm** [comment]
Great feature. Is working on my system with Admin 6.1.1
In my oppinion this issue can be closed.
