### ISSUE TITLE
After importing SSL cert, admin instance not started: PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by JB1985** [ioBroker/ioBroker.admin#1212]
**Describe the bug**  
SSL Certificate is probably not imported correctly.

**To Reproduce**  
1. Go to 'Settings' -> 'Certifiate'
2. Click on 'Plus' to add a certificate

**Expected behavior**  
Import the SSL certificate. Iobroker admin is not starting.

**Screenshots & Logfiles**  
 
![image](https://user-images.githubusercontent.com/9932751/143459095-76b9cb49-603e-43e6-9b95-25a1a29e2cc8.png)

Errorlogs:

error: admin.0 (6930) Cannot create web-server: Error: error:0909006C:PEM routines:get_name:no start line

**Versions:**  
 - Adapter version: 5.1.28
 - JS-Controller version: 3.3.20
 - Node version: v12.22.7
 - Operating system: Raspbian GNU/Linux 10

**Additional context**  
I deleted the old certificate and wanted to upload the new one. Now the instance does not start.

**Comment by JB1985** [comment]
I have imported a backup. I copied and re-imported the old (working) certificate and this is not working too.

It looks like the certificate will be broken when importing.

BTW: Same with v.5.1.29

**Comment by poldiderjungdrache** [comment]
I suggest check you _cert in the screenshot it looks to me like there is a space after BEGIN CERTIFICATE----- that should not be there. Also check the rest of the cert string maybe there are some more unwanted characters

**Comment by JB1985** [comment]
I have try without space, utf8, ascii, firefox, chrome .... i have try a lot ...

![image](https://user-images.githubusercontent.com/9932751/143538755-0672c199-36a8-4895-8d43-11e60c8fd8e0.png)

All imported certs are not working.

**Comment by Apollon77** [comment]
normally I would have expected \r\n or such after the --

**Comment by JB1985** [comment]
Same with v5.2.0

**Comment by JB1985** [comment]
Strange ... Drag & Drop is working but not manuelly copy&paste!

**Comment by Apollon77** [comment]
But on "copy&paste" what exactly you copy? It seems that linebreaks are getting lost ... so maybe "the way you copy"?

**Comment by SirHis** [comment]
Hello,

i have the same problem since two weeks. 
If i insert a new certificate and a private ( public / private) key, with copy & paste / drag & drop / with the absolute filenames the instance raise an error at the next restart:

admin.0 | 2021-12-08 16:43:39.652 | error | Cannot create web-server: Error: error:0909006C:PEM routines:get_name:no start line
-- | -- | -- | --

In the iobroker forum i didn't find an actual hint to this problem.

What can i do to solve this?

**Comment by Apollon77** [comment]
How the file looks like? How the config looks like?

**Comment by SirHis** [comment]
I hope this is what you want:
Basiskonfiguration - Zertifikate:
![grafik](https://user-images.githubusercontent.com/25884300/145273957-c58af3fa-6a48-49fa-92d0-9880e4d0aca7.png)

![grafik](https://user-images.githubusercontent.com/25884300/145274541-918ca580-eb22-46e3-bbc4-1fa33469d4ec.png)


HTTPS- Konfiguration:
![grafik](https://user-images.githubusercontent.com/25884300/145274754-df423212-a96f-44db-b4b7-07f2d9753a3b.png)

**Comment by Apollon77** [comment]
Yes also here are the Line breaks missing ... so the content is invalid

**Comment by SirHis** [comment]
Sorry, i don't understand. 
The private key and the certificate (public) are created in the same way like other. These other Certificates / Keys are functional on some other computer and webservern (raspberrymatic, webmin, qnap nas, openmediavault nas, proxmox ve, opnsense) without any problems.

What is the real reason and how can we solve it?

**Comment by JB1985** [comment]
Drag&Drop worked for me.

**Comment by SirHis** [comment]
@JB1985 : Unfortunately not with me. 

In the meantime I made one more attempt:
Transferred the two files ( which were fine - with line breaks) with FTP to the target system. Then the files were checked again on the target system - they are with line breaks. In the IOBROKER - basic settings the files were then included via the absolute path ( '/opt/certs/lxc-iobroker4_private.pem', /opt/certs/lxc-iobroker4_public.pem'. The result after restarting IOBROKER and the admin.0 module is the same error.

**Comment by SirHis** [comment]
Please, can you tell me where the content of the Certificate and PrivateKey in the iobroker-system are stored? In which format?  How can i see if the key/certificate are ok?

**Comment by SirHis** [comment]
At a last try I got the module ADMIN with SSL encryption (HTTPS) to run!
Solution: After the two files ( private Keyand public Cert.) were successfully transferred to the IOBroker server and checked, the absolute file names were entered in the corresponding assignments of the base configuration. Likewise the appropriate assignment in the configuration for HTTPS (private and public) in the ADMIN module took place.

i.e. base configuration:
public /opt/cert/public_key.pem
private /opt/cert/private_key.pem   
  
In this notation the ADMIN - module starts without errors.
The given notation on the configuration page of the base configuration with a simple check mark above is wrong - or I misunderstood what the author wanted to tell me.

Another little hint: The line breaks in the two key files must of course be in UNIX/LINUX format (0x0a) (not in Windows format!).

The way with drag and drop or copy and paste still does not work for me!

**Comment by peer69** [comment]
I have been running into this problem after updating to js-controller 4.0.4. 
I am now unable to even select my additional cert and key for the admin adapter via drop down selection. Only the self signed default cert/key show up. For web and simple-api I can select my custom cert/key just fine.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/28559804/152756704-727f7a41-1a30-4c40-b742-d38595e3ceaa.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/28559804/152756809-59cec535-c024-4bf1-a6fe-302edab934d7.png">

**Comment by captaindork** [comment]
> I have been running into this problem after updating to js-controller 4.0.4.
> I am now unable to even select my additional cert and key for the admin adapter via drop down selection. Only the self signed default cert/key show up. For web and simple-api I can select my custom cert/key just fine.
> <img alt="image" width="600" src="https://user-images.githubusercontent.com/28559804/152756704-727f7a41-1a30-4c40-b742-d38595e3ceaa.png">
> <img alt="image" width="600" src="https://user-images.githubusercontent.com/28559804/152756809-59cec535-c024-4bf1-a6fe-302edab934d7.png">

Hi, I ran into this today as well, however it worked for me when using Chrome instead of Edge to open admin. Maybe this works for you as well!

**Comment by DerRonX** [comment]
I had same problem, that own ssl certs not working.
After inserting my own certs, the admin adapter not started.

My old workaround: 
- removing SSL for admin adapter
- starting old user interface
- inserting my own certs
- reboot
- changing back to Admin 5.X
working...

My new workaround:
- stopping iobroker
- editing objects.jsonl by inserting my certs including "\r\n" for line seperator
- restarting
working...

Looks like there is a different handling from old user interface to new interface.

At the new interface it doesnt matter how I inserting the certs the result is not as expected...

**Comment by hollywoot** [comment]
Same problem here.
![Screenshot_20220531_091408](https://user-images.githubusercontent.com/102350398/171114252-3bc03862-4355-4492-bfac-05c65f2cd366.png)
![Screenshot_20220531_091441](https://user-images.githubusercontent.com/102350398/171114359-304b57d8-c89f-4c93-a4fb-71867dd0e81a.png)

Its interesting: the web.0 can find the certificate & key, the admin.0 can't.
![Screenshot_20220531_091441](https://user-images.githubusercontent.com/102350398/171114505-eb391b0b-75f6-4060-984b-8d6f1fcc8eba.png)

If I try to edit the object.jsonl, I can see some old certificates that Ive allready deleted.

**Comment by Diginix** [comment]
You have to name all with suffix private/public, as mentioned here: https://github.com/ioBroker/ioBroker.admin/issues/1212#issuecomment-991293950

![image](https://user-images.githubusercontent.com/39678667/171115254-47a8d230-7ec0-4ff4-a0de-af5c6794b93f.png)

**Comment by hollywoot** [comment]
Thanks for reply. 
This solved my problem! Wtf :)

**Comment by Feuer-sturm** [comment]
@SirHis Thanks for your feedback.

Can you please describe more detailed (with screenshots if it helps for understanding ) what needs to be optimized from your point of view?

**Comment by BoehserWolf** [comment]
I'm not able to get self signed certs visible in Web-GUI at all. I'm running Admin 6.3.5, js-controller 4.0.24, node/nodejs 16.19.0 and npm 8.19.3.

For private and public tried with and without underscore and also with first letter uppercase and not.
Tried to paste the cert and key directly in the textboxes, gave an extra space and removed it again.
Last and current setup with files on the filesystem also with no luck:

![grafik](https://user-images.githubusercontent.com/7871719/210280115-0c82a460-7389-49fc-aa12-2d179b72f787.png)

File permissions for the sake of completeness:
`boehserwolf@iobroker:/opt/iobroker:$ ls -al /srv/mycerts/ioBrokerWebGui.*
-rw-r--r-- 1 iobroker iobroker 2362 Jan  2 22:40 /srv/mycerts/ioBrokerWebGui.crt
-rw-r--r-- 1 iobroker iobroker 3268 Jan  2 22:40 /srv/mycerts/ioBrokerWebGui.key
`

Did a restart of admin.0 after each change of any cert.

If you want me to do something let me know.

**Comment by Apollon77** [comment]
Der Name ist an sich egal ... Steht irgendwas im Log?

**Comment by BoehserWolf** [comment]
Wenn ich das Zertifikat neu hinzufüge steht nichts im Log.

Nach Neustart der admin.0 Instanz auch nichts Hilfreiches:
2023-01-03 10:54:42.618  - info: host.iobroker stopInstance system.adapter.admin.0 (force=false, process=true)
2023-01-03 10:54:42.624  - info: admin.0 (1658124) Got terminate signal TERMINATE_YOURSELF
2023-01-03 10:54:42.625  - info: admin.0 (1658124) terminating https server on port 8081
2023-01-03 10:54:42.627  - info: admin.0 (1658124) terminating
2023-01-03 10:54:42.628  - info: admin.0 (1658124) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-01-03 10:54:42.662  - info: host.iobroker stopInstance system.adapter.admin.0 send kill signal
2023-01-03 10:54:42.618  - info: host.iobroker stopInstance system.adapter.admin.0 (force=false, process=true)
2023-01-03 10:54:42.624  - info: admin.0 (1658124) Got terminate signal TERMINATE_YOURSELF
2023-01-03 10:54:42.625  - info: admin.0 (1658124) terminating https server on port 8081
2023-01-03 10:54:42.627  - info: admin.0 (1658124) terminating
2023-01-03 10:54:42.628  - info: admin.0 (1658124) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-01-03 10:54:42.662  - info: host.iobroker stopInstance system.adapter.admin.0 send kill signal
2023-01-03 10:54:43.232  - info: host.iobroker instance system.adapter.admin.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-01-03 10:54:43.232  - info: host.iobroker instance system.adapter.admin.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-01-03 10:54:45.745  - info: host.iobroker instance system.adapter.admin.0 started with pid 1659163
2023-01-03 10:54:45.745  - info: host.iobroker instance system.adapter.admin.0 started with pid 1659163
2023-01-03 10:54:46.452  - info: admin.0 (1659163) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2023-01-03 10:54:46.558  - info: admin.0 (1659163) starting. Version 6.3.5 in /opt/iobroker/node_modules/iobroker.admin, node: v16.19.0, js-controller: 4.0.24
2023-01-03 10:54:46.604  - info: admin.0 (1659163) requesting all states
2023-01-03 10:54:46.604  - info: admin.0 (1659163) requesting all objects
2023-01-03 10:54:46.452  - info: admin.0 (1659163) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2023-01-03 10:54:46.558  - info: admin.0 (1659163) starting. Version 6.3.5 in /opt/iobroker/node_modules/iobroker.admin, node: v16.19.0, js-controller: 4.0.24
2023-01-03 10:54:46.604  - info: admin.0 (1659163) requesting all states
2023-01-03 10:54:46.604  - info: admin.0 (1659163) requesting all objects
2023-01-03 10:54:47.219  - info: admin.0 (1659163) received all objects
2023-01-03 10:54:47.302  - info: admin.0 (1659163) https server listening on port 8081
2023-01-03 10:54:47.304  - info: admin.0 (1659163) Use link "https://localhost:8081" to configure.
2023-01-03 10:54:47.307  - info: admin.0 (1659163) Secure socket.io server listening on port 8081
2023-01-03 10:54:47.520  - info: admin.0 (1659163) ==> Connected system.user.admin from 192.168.114.6
2023-01-03 10:54:47.219  - info: admin.0 (1659163) received all objects
2023-01-03 10:54:47.302  - info: admin.0 (1659163) https server listening on port 8081
2023-01-03 10:54:47.304  - info: admin.0 (1659163) Use link "https://localhost:8081" to configure.
2023-01-03 10:54:47.307  - info: admin.0 (1659163) Secure socket.io server listening on port 8081
2023-01-03 10:54:47.520  - info: admin.0 (1659163) ==> Connected system.user.admin from 192.168.114.6

admin.0 "sieht" das Zertifkat nicht:
![grafik](https://user-images.githubusercontent.com/7871719/210335270-9e36c1eb-6344-4672-8e97-1ff7489a4850.png)

web.0 allerdings schon:
 
![grafik](https://user-images.githubusercontent.com/7871719/210335446-a786ac79-590e-4e14-bccd-9cc686b7a65b.png)

Kann ich sonst noch etwas liefern?

**Comment by Apollon77** [comment]
Ok, mit den Infos,muss Bluefox schauen

**Comment by foxriver76** [comment]
Please re-check with current admin version, else open a new ticket, here are some separate topics contained in this ticket.
