### ISSUE TITLE
Show Write-State on Object-View

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1317]
Display the write status of a data point ("write": true/false) in the object view. A small graphic (an open lock?) would suffice.

**Comment by darkiop** [comment]
Hi Ingo, sorry - missed the answer.
First and foremost, the idea was to be able to see directly (especially with new, still unknown objects) which are intended for the writing process. So more of a "getting to know". Currently I'm always clicking through the RAW of the DP.
I knew that as an "expert" I could write anything, but that rarely makes sense to do so ;)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/171859472-726b4b81-6a20-4e40-aa6e-95b77d29140d.png)
Implemented in Admin6

**Comment by Apollon77** [comment]
I'm not sure if this * is really "underatsndable" ... Dumb question: why not extending the "state value mouseover-thingy and add a writable: yes or such at the bottom, maybe after a line break or such?

**Comment by mickym2** [comment]
Instead of using the value column to reflect the changeable status of the state, put a lock (open or locked) into the settings column. If change the read/write status you can directly change it there or you just ignore this or grey it out. 

![image](https://user-images.githubusercontent.com/58858526/171999208-b4e082d5-c829-4094-b9b7-12d76344dfe6.png)

**Comment by Apollon77** [comment]
I think colors are already used for quality, so they are "no option" in my eyes - we wopuld only have the background color :-)

**Comment by GermanBluefox** [comment]
Changing of background colors looks terrifying

**Comment by GermanBluefox** [comment]
> Instead of using the value column to reflect the changeable status of the state, put a lock (open or locked) into the settings column. If change the read/write status you can directly change it there or you just ignore this or grey it out.
> 
> ![image](https://user-images.githubusercontent.com/58858526/171999208-b4e082d5-c829-4094-b9b7-12d76344dfe6.png)

It will take too much place

**Comment by Apollon77** [comment]
Then maybe really makeing the tooltip with value "Longer "by adding a writeable" at the end or such

**Comment by Apollon77** [comment]
![2022-06-09 13 04 34](https://user-images.githubusercontent.com/11976694/172832627-72bbd0e9-4c77-40e2-bf1d-99deaeb75a4f.jpg)
Somewhere there a red "readonly" if not writebale ... or a green "writable"  es would be not on the first view but still easy accessable

Alternatively we could add it only in the "pencil dialog" where you can set a value and show a red warning "please not this state is not writeable...."

**Comment by Diginix** [comment]
I would prefer the tooltip. There is enough space and it is a not that much important information that it needs an icon or color in the object table.

**Comment by Grizzelbee** [comment]
> Changing of background colors looks terrifying

I expected that. ;) 

> I would prefer the tooltip.

I don't really like the idea - because you don't get the information "on first sight" - where it would be needed. It will be really annoying to hover over each and every state and wait for the tooltip to get the information. When you examine a new adapter this would take ages.

What about a second - vertical standing - pencil in green und red? This would take only a few pixels.

**Comment by GermanBluefox** [comment]
> I get a warning in the log - but why is it possible at all to write a value?

I want it. For tests purposes

**Comment by GermanBluefox** [comment]
> I would prefer then - and do not see the problem why the button to write is not just diabled: ![image](https://user-images.githubusercontent.com/58858526/172837704-69437aa3-561a-460b-afcd-6869e8731071.png)
> 
> I get a warning in the log - but why is it possible at all to write a value?

This is good idea: 
![image](https://user-images.githubusercontent.com/4582016/172841870-e5110cb0-a0cc-4835-b162-9b8f5b2e263a.png)

But of course it should be somehow shown in main table

**Comment by GermanBluefox** [comment]
> What about a second - vertical standing - pencil in green und red? This would take only a few pixels.

There is no place for any pencils. Read the issues and you will understand that people trying to work with admin on mobile devices and claiming, that they do not see all information

**Comment by Apollon77** [comment]
maybe really a different color of the "set value" button together with a red note when it is readonly

**Comment by Grizzelbee** [comment]
But ... wasn't the initial idea/request to get a better overview in the device tree which states are writeable or readonly? At least that's what is currently implemented.
Maybe I don't understand it at all - so it may be better to remain silent.

**Comment by Apollon77** [comment]
Yes you are right ... but the options are not that easy, or? So we just discuss alternatives that also "at least allow to see it when needed". In fact it is only an issue also in "expertmode" or?

**Comment by Grizzelbee** [comment]
I'm sorry - but not from my perspective. 
I would love to be able in std. mode to see directly in the device tree whether a state is intended to be switched (writeable) or delivers a plain information (readonly). Just like it is right now. Thats pretty perfect - my only point was, that the asterisk isn't the perfect solution - since it looked like dirt on my screen at first sight.
Currently I'm (from a simple user perspective) able to see at one sight whether a state is intended to be editable or not in all views. 

That's awsome! A great benefit when testing/getting familiar with new adapters or connecting states to a gui.

![grafik](https://user-images.githubusercontent.com/5459426/172856045-4c5a5301-5ed2-4b39-ba32-3d8d4cf08684.png)

Maybe the paper sheet in front of the states delivers an option:
* Red outlined with an R inside for ReadOnly
* Green outlined with an W inside for Writeables
The color/letter combination even won't leave the color blinds behind.

**Comment by mickym2** [comment]
> I'm sorry - but not from my perspective. I would love to be able in std. mode to see directly in the device tree whether a state is intended to be switched (writeable) or delivers a plain information (readonly). Just like it is right now. Thats pretty perfect - my only point was, that the asterisk isn't the perfect solution - since it looked like dirt on my screen at first sight. Currently I'm (from a simple user perspective) able to see at one sight whether a state is intended to be editable or not in all views.
> 
> That's awsome! A great benefit when testing/getting familiar with new adapters or connecting states to a gui.
> 
> ![grafik](https://user-images.githubusercontent.com/5459426/172856045-4c5a5301-5ed2-4b39-ba32-3d8d4cf08684.png)
> 
> Maybe the paper sheet in front of the states delivers an option:
> 
> * Red outlined with an R inside for ReadOnly
> * Green outlined with an W inside for Writeables
>   The color/letter combination even won't leave the color blinds behind.

In my opinion it must not be outlined bat an Icon with an "r" in it and a blank icon would be sufficient as well. So no additional space is needed but is noticeable at once.

**Comment by GermanBluefox** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/4582016/172861942-ae40cd40-c8d0-49e1-9201-56c5ec0c1c61.png)

**Comment by mickym2** [comment]
> Like this? ![image](https://user-images.githubusercontent.com/4582016/172861942-ae40cd40-c8d0-49e1-9201-56c5ec0c1c61.png)

Exactly :)

**Comment by Grizzelbee** [comment]
Not perfect - but okay. It's the most minimalistic way. And the lock look a bit bold to me.
I don't really like the absence of an information to be interpreted as an information (lock/no lock). 
Therefore I still prefer something in the sense of my proposal. 
* r/w for readOnly/writeable; 
* i/s for information/switch (even when switch doesn't perfectly fit here to the role="switch"; but in the end something gets changed)
* i/c for information/changeable
* open lock/closed lock

color is optional - I agree; but fancy. ;-) And may eventually help with the bold lock.

**Comment by mickym2** [comment]
Another option could be the state icon with the lock under type - to put a lock inside (but this disappears if you switch to the time view) - but matches probably more the meaning to visualize a "read-only" state. The advantage to have in the type or role column would be that you can filter to read-only states as well.

**Comment by Apollon77** [comment]
Adjusting the icon is a great idea ... maybe turn it around? icon with a pencil icon for "editable"? and nothing for not?

**Comment by GermanBluefox** [comment]
I implemented it already. if someone does not like it. PR is welcome. Here: https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/components/ObjectBrowser.jsx#L3961

**Comment by Grizzelbee** [comment]
@GermanBluefox 
No need to react that grumpy.
The only further change @Apollon77 and me suggested>/considered/discussued in the ongoing discussion was to change the additional icon to a pencil instead of a lock since it seems to be more intuitive to us in that context. 
If discussions and ideas aren't welcome I'll stop it. I'll find another way to waste my time.
