### ISSUE TITLE
Screen "Update all adapters" does not show all available updateable adapters

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1437]
**Describe the bug**  
7 Adapters have an update but if I opfen adapter gui to update all adapters at once only 5 of them are shown. In my case Admin and Fritzbox is missing

**To Reproduce**  
1. Go to Adapter menu
2. Click on "Alle Adapter aktualisieren"
3. Not all adapters are visible which can have an update available

**Expected behavior**  
All adapters which can be updated will be shown

**Screenshots & Logfiles**  
Admin 5.3.4
![grafik](https://user-images.githubusercontent.com/25422320/164553292-a91760b7-2449-42de-835e-1a43d1f31afe.png)
![grafik](https://user-images.githubusercontent.com/25422320/164553369-a7a8f48c-4b05-4152-add1-4d9b47a0452f.png)

**Versions:**  
 - Adapter version: Admin 5.3.4
 - JS-Controller version: 4.0.21

**Comment by Feuer-sturm** [comment]
After update to Admin 5.3.8 6 adapters have an update but in Screen for Update all adapters only 5 adapters are shown. Fritzbox is still missing.

**Comment by klein0r** [comment]
- Admin is missing, because it is not updatable via "update all adapters"
- Fritzbox is missing, because the io-package.json contains an important message for the user which has to be confirmed before the update. *Normally the update button has another color (orange?) in list view when there is such a message.*

In my opinion everything is correct.

https://github.com/iobroker-community-adapters/ioBroker.fritzbox/blob/4d3bdfbf66e1b9fcc3cfd3439bfe18bacf870d94/io-package.json#L103-L143

**Comment by klein0r** [comment]
Example for mqtt 3.0.6

<img width="647" alt="Screenshot 2022-04-26 at 15 47 06" src="https://user-images.githubusercontent.com/1959049/165314437-cfbdff07-4035-459c-87ba-e454ae82332b.png">

**Comment by GermanBluefox** [comment]
Yes. It is really because of important message.
