### ISSUE TITLE
Error in GUI: #tab-adapters/readme/iqontrol

### ISSUE THREAD

**Issue by jensb** [ioBroker/ioBroker.admin#1567]
**Describe the bug**  
Error in GUI when opening the info page about the iqcontrol widget.

**To Reproduce**  
Open the iqcontrol widget info.

**Expected behavior**  
iqcontrol widget info should be displayed.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/44540/176651568-59718510-0286-463c-aabb-ad6c340a622b.png)

**Versions:**  
 - Adapter version: 5.3.8
 - JS-Controller version: 4.0.23
 - Node version: v14.19.0
 - Operating system: Raspbian 64bit

**Additional context**  
This is reproducable. Restarting iobroker does not help.

**Comment by GermanBluefox** [comment]
Please use latest admin for that

**Comment by jensb** [comment]
The "Latest admin" for me is 5.3.8, at least in the ioBroker GUI. This I have installed.
How do I get a newer version?

**Comment by Feuer-sturm** [comment]
@jensb Hello, 5.3.8 is the current stable Version. In beta Repository the Version 6.1.8 is currently available. This Version is in beta Status and currently under testing. For Production systems it is recommended to use the stable version. 
If beta Phase is finished admin 6 will get stable.

**Comment by jensb** [comment]
Yes, exactly. So it cannot be expected to upgrade to a non-stable admin adapter version to fix the above issue. Right?
Please reopen. The IQcontrol info page should work wirg stable admin as well. IMHO.

**Comment by Apollon77** [comment]
The process is that an adapter gets updates and this is in Beta repo first. Then after some time and ideally positive feedback of the users the new version will come into stable.

So yes, in some time also the stable version contains the fix.

In fact the bug shoud be fixed in the said version, so we close the Admin issue.
you have two options: Update Admin to Beta version and wait until the new Admin version will come into stable. This do not change anything regarding "there is a version where this is fixed".

Handling GitHub issues and just closing them when a version becomes stable is horror in efforts and so we can not consider this.

I hope this makes it a bit more understandable

**Comment by jensb** [comment]
I understand completely, thank you.
However, I was expecting (real) bugs to be fixed in the stable versions as well, in parallel to development of new features.
This is why we can have multiple Git branches, right?
And I do consider this a "real bug".

IMHO: Users should not be expected to install beta or development versions just to have a bug fixed.
But that's just MHO.

**Comment by Apollon77** [comment]
Hm ... an issue with showing a readme of one of 450+ adapters? I, from the overall project and admin complete featureset perspective, would not see that as an important bug because also you are the only one as it seems that found that ... and it is not a overall functional bug and also not blocking. 

I see this as a "severity C bug" (on a Show Stopper, A, B, C scale) because it is a minor feature and nt in a normal important user flow. Alone doing such a discussion ablout "bug severities" will not lead to any "common" answer because each user will have a different opinion here and maybe the developer even an other one.

In fact yes, working with multiple branches and differentiating hotfix releases and feature release can be done that way. But this means an enormous amount of management effort to make that in a way that it works - and then the fix is still not verified and in worst case might break other stuff. ioBroker adapter usually do not have QA departments that take care of such testing as in "business situations" where such release strategies work. We are in a community driven situations here! Or do you offer support in testing Admin adapter on solved issues and new features and such in general ? ;-)

Thats why the process here is that a new version with fixes and/or new features is delivered to the Beta channel first and after testing by the Community members that decided to use Beta versions it is put to stable. And depending how important bugs are the time how long it stays in beta differs and migth be shorter.

IF a user really needs a bugfix he can install a Beta version once to workaround an issue and can also go back to stable if something is not ok here. We are  very flexible here.

In fact the usual waiting time for a new version to come to Stable is roughly 15days (then the developer gets reminded with infos on how much the new version was used so far). In this case Admin 6 is a bigger step so it takes a bit longer.

**Comment by jensb** [comment]
If the turnaround between beta releases and stable releases is indeed just 15 days, I'm good. No worries, I didn't know about that.
I just feel that bugs should be pushed to stable ASAP. Especially show stoppers (which make something unuseable) and security bugs.
But for non-security bugs 15 days is fine.
Thanks for your explanation. :-)
