### ISSUE TITLE
Ignore logs in a specific timespan per adapter instance

### ISSUE THREAD

**Issue by aortmannm** [ioBroker/ioBroker.admin#1572]
Every night I have my 24h internet disconnect and I have some adapters that throw errors because of this. It would be great if I can set a timespan where my 24h disconnect is that the logs for the specific adapters are ignored.

Right now I always need to login and clear the log because of the errors. I just wanna see unexpected errors.

**Comment by Ilovegym66** [comment]
You mean like a whitelist for warnings / etc? 
Good idea 👍

**Comment by aortmannm** [comment]
Yeah this would work too. Would be a really great feature

**Comment by Apollon77** [comment]
Hm ... sorry but I think this is no good idea because who defines what "expected errors" are and what not? And how? "Contains text"? "Regex"? Timeframe?

Just ignoring logs because of a timeframe will hide any other issues in this timeframe and then users come with "yes but THHHHIIIISSSSS error is important, just some others not" ... 

So this feature would require to develop a KI that can decide between important and unimportant logs based on individual users ;-) (yes, ironic)

I more think that you misunderstand for what log files and logs are for ... they are there to check the system in case that there is something and yes humans read logs to decide if there is really something.

Just my 5 cents for that

**Comment by aortmannm** [comment]
Why? You can just add an whitelist feature as @**[Ilovegym66](https://github.com/Ilovegym66)** said and than everybody can add his own list of error's that are default for his automation part?

For me an error should be something unexpected and if I daily have a red protocoll/log with errors because of a normal 24h disconnects than it's not the correct way for me.

**Comment by Apollon77** [comment]
Ok, what is an error? it is a Text and it can be "Multiline", it can contain "dynamic parts" (if you think it further), so static string matching will not really do the job well when I assume user expectations :-)

Additionally when we should do that? Checking for each Logline which is send to the system a bunch of regex or texts? Have you any idea what this will do to any system in regard of performance (and I do not even start thinking about the Raspi 1+2's out there - they will be on 100% as soon as you setup ONE whitelist entry). So it can not be a general thing. This will never work. (And before you as: yes also any silly or debug logline would be checked because the logging system works that way right now and the used library currently do not offer additional checks "Just before a line is written out".)

So we could think about that just for Admin displaying logs (so it will still be in the logfile on disk), just Admin will not show it (and I hear again users that say "Hey no, I do not want to see it at all) ;-) But even then the browser or server needs to check an "undefined long list of texts to ignore" when getting logs shown.

> For me an error should be something unexpected and if I daily have a red protocoll/log with errors because of a normal 24h disconnects than it's not the correct way for me.

So you expect that the logfile is "for you"? Sorry, but the reality is that a logfile is "For the software system telling about stuff that might be interesting for the user". You decide if you hear it or ignore it. The software system do not know of any 24h internet disconnects and the system is also not initiating them, so the software system is dumb in that regard

**Comment by aortmannm** [comment]
Ok, I understand what you mean but than we could probably think about another thing.

When I now have an error/warning in the Protokoll I have the red little Number in the menu of the left side. After I read the errors/warning it shouldn\t be red anymore when I open ioBroker in a new tab because I still have read the errors and acknowledged it?

Probably this could be a thing?

**Comment by Apollon77** [comment]
The problem is exactly "multiple Tabs" ... Admin is a "browser application" that runs 100% in your browser ... so the "instance" you run in that tab where you read the logs and that resets the "UI info red thing" the other instance that runs in your other tab do not know about the action you did. Difficult ...

**Comment by Apollon77** [comment]
PS: This would be a topic to discuss in an other topic ... but would require that all tabs exchange infos all the time to sync such "status" stuff ... but what to sync and what no? ;-)

**Comment by GermanBluefox** [comment]
We have such a request, that will be implemented in "I have no idea" time or may be will not be implemented at all: https://github.com/ioBroker/ioBroker.admin/issues/1487

**Comment by GermanBluefox** [comment]
This will be never implemented
