### ISSUE TITLE
Admin Anzeige NPM Version wird falsch geholt

### ISSUE THREAD

**Issue by Glasfaser-io** [ioBroker/ioBroker.admin#1663]
Wie mal im Thread herrausgefunden hat  wird die falsche NPM angezeigt,
der Admin schaut also auf das ACTIVE Release Bundle

https://forum.iobroker.net/topic/56586/admin-6-2-3-warnung-cannot-find-npm-version/15?_=1661521216080

![grafik](https://user-images.githubusercontent.com/89259953/186917233-5b65c572-8c11-44e4-b0c5-6914d15acdfc.png)

Auch hier :
https://forum.iobroker.net/topic/57485/wie-wird-denn-npm-geupdatet

**Comment by GermanBluefox** [comment]
Nein. Es wird nicht die falsche NPM angezeigt. Man kann npm immer noch mit `npm i npm@latest -g` updaten

**Comment by Grothesk242** [comment]
Es sollte aber nicht die upstream Versionsnummer sondern die für das jeweilige Release von Bodens vorgesehene npm Version angezeigt werden. 
Alles andere verleitet nur zu unnötigen Installations/Upgrade-Versuchen.

**Comment by Apollon77** [comment]
@GermanBluefox @Grothesk242 hat recht ... wurde schon mehrfach diskutiert. Eigentlich wollen wir nicht das user manuell an npm rumändern und updaten. Das hat bisher öfters zu issues geführt. Die npm version die bei der node.js version dabei ist die wir empfehlen wäre das ziel ... (der linux installer schaltet auch aus das npm immer über neue versionen informiert ... verwirrt user nur weil Sie denken sie müssen updaten).

Von daher wäre es cool (enhancement) wenn die npm version von wo anders geholgt wird sodass sie zur aktuellen (oder empfohlenen) nodejs version passt.

**Comment by dekatWin** [comment]
I have the same problem but with the Node.JS version, it is correctly recognised under the Info Adapter, but when I try to update an adapter, node.js 12x is always displayed. For me, the problem is probably due to the messy Node.JS update. I use Iobroker on Windows and am therefore forced to change the inside of some Node.js folders. I am currently using Node.JS 16.x and I have been forced to update my Adapters via the Console as Admin no longer allows me to do this via the GUI.

It would be great if you could allow an Adapter update with the wrong version after receiving a clear warning that you should not do this.

**Comment by GermanBluefox** [comment]
> Es sollte aber nicht die upstream Versionsnummer sondern die für das jeweilige Release von nodejs vorgesehene npm Version angezeigt werden.

Wer hat das gesagt?

**Comment by Grothesk242** [comment]
Die Erfahrung sagt das.

**Comment by Apollon77** [comment]
Thank you!
