### ISSUE TITLE
State wird als Folder dargestellt.

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.admin#1772]
**Describe the bug**  
State will be displayed as folder, when it holds states itself, see https://github.com/Zefau/ioBroker.jarvis/issues/2010.

![image](https://user-images.githubusercontent.com/14368811/198871284-70116f2c-5343-41c4-806f-b839ee93192a.png)

**Expected behavior**  
Only the state is shown without the child-states AND / OR and error should be displayed in the ioBroker.log.

**Additional context**  
ioBroker defines and follows rules, which are also very important for developers to predict a certain behavior with their implementation. From my understanding the different types (device, channel / folder and state) have a meaning, which should be followed consistently.

**Comment by Apollon77** [comment]
In fact this is not a bug!

On eone hand Admoin shows anything which is not "after the last ." in the state as folder icon because it traverses the structure separated by "."

So the "error" is that there is a "state object" which is not on the "last level", because this should not be!

I know that some adapters maybe have such structures as they first hasd a state and later added more "sub data" and so it stayed that weay because of backward compatibility ... but in fact the structure is wrong.

How should admin display that else?

So in fact admin does his best to discplay the structure - the state object on the wrong level is the "issue"

**Comment by Apollon77** [comment]
PS: To prevent such "strange" structures from happening would be a breaking change and someadapters needs to be adjusted ... in fact till now we decided against it. If you want to start a discussion about this please open a js-controller issue because this would be the place to enforce it

**Comment by Zefau** [comment]
Thanks for the quick answer.

I fully understand, but my point is not to avoid it from being shown by the admin adapter but rather to show an error message or warning in the log.

This would make the user report to the respective adapter / developer to change it.

**Comment by Apollon77** [comment]
I donot think that it makes sense that Admin shows an error (admin could only do in browser console where noone sees anything at all) because server side do not know it. SO rather this also would be a "js-controller " topic when such objects are created ... but no idea if we can have a performant solution here because it would requoire to know sub objects when creating an object ... I'm not sure ... as said: When I would see this a discussion in js-controller

**Comment by Zefau** [comment]
Same for me. I don't care whether here or js-controller. 

From a developer perspective I would just appreciate certain rules and their enforcement. This topic is one of them. Another topic would be white spaces in ioBroker States / Objects. 

Jarvis rejects whitespaces but certain adapters create such states / objects. 

All adapters breaking such rules should at least be "punished" with a warning or error in the log. Wherever it comes from.

**Comment by Apollon77** [comment]
> Jarvis rejects whitespaces but certain adapters create such states / objects.

Do you have an example? Normally there is a logic in js-controller which replaces all not officially allowed characters by "_" ...

**Comment by Sineos** [comment]
To add to this discussion: The screenshot in the original post is from iobroker's standard mqtt broker / client. This is how the mqtt adapter builds the tree from a zigbee2mqtt instance.
You are right, @Apollon77, the structure is build "sequentially" as new DPs pop up whenever zigbee2mqtt publishes a new state.

**Comment by Apollon77** [comment]
Yes especially the mqtt adapter can only follow what comes in to the system. And yes especially in mqtt such structs can happy also if we all do not like it (in fact also for MQTT not a clean structure to have data on "in between structure levels" but mqtt allows that and so devices and such use that also ... 

And in this exact case the adapter _can not_ prevent it because else we have the next users in an mqtt thread that tell that data are missing when they are sent that way ... trallallaaa .... ;-))
