### ISSUE TITLE
new admin not always show actual objects status

### ISSUE THREAD

**Issue by vladitep** [ioBroker/ioBroker.admin#196]
![untitled-3](https://user-images.githubusercontent.com/24714809/36141609-5a0b781c-10b6-11e8-877c-96826800954d.jpg)

**Comment by GermanBluefox** [comment]
I am rather sure you build your objects wrong. States May not have
sub-states. Only channels and devices may have states.

13 февр. 2018 г. 10:06 пользователь "vladitep" <notifications@github.com>
написал:

**Comment by vladitep** [comment]
at first - wrong states show at objects who not have any sub-states, for second it's not explain, why in admin and in vis editor  shows different states. its
and in older version admin and vis editor show identical states

**Comment by vladitep** [comment]
so, make it clear - you try to say me what its is not a bug when admin not refresh object states whereas of vis editor did?

**Comment by Apollon77** [comment]
Bluefox, what is the logic for subscribes in Admin3?!!

Currently iobroker is very „nice“ and allows Rinder a state value for nearly anything. Independent if it is a state, channel or device... so existing scripts and partially Adapters too maybe do „unintended“ stuff :-( 

And for those the effect is now that the state values are not updated in admin3 ...

We should be transparent here on „the rules“ and „intended usage“ ...

**Comment by GermanBluefox** [comment]
The rules are simple: only channels and devices May have sub-states.

13 февр. 2018 г. 22:00 пользователь "Ingo Fischer" <notifications@github.com>
написал:

**Comment by Apollon77** [comment]
Then we will have big problems especially with custom JavaScript states because very often people simply createState(„bla.blubb.fasel“,...) ... and using Blockly you simply can not create channels or devices. :-(

So we should have special rule for javascript.* States !! 

For Adapters we can make sure it is clean but should add warnings if someone creates states without needed channels or devices ...

**Comment by vladitep** [comment]
Устал я по английски. Окей, это твое детище и ты решаешь как его развивать, но ты не можешь не знать что уже созданные стейты нельзя переделать в обьекты и каналы, такого функционала нв брокере нет. Под новую админку надо полностью с нуля переделывать структуру обьектов умного дома, это нихрена себе изменение чтобы о нем так вскользь упоминать.
О том что новая админка может быть не совмеситима со структурой обьектов сисетмы надо писать огромными буквами в трех местах, а не щипцами из тебя это вытягивать. И уж тем более такую админку в продакшн с заменой старой выкатывать нельзя, это просто неуважение ко всей твоей армии юзеров, тестеров и разрабов.

**Comment by GermanBluefox** [comment]
Так много желчи. Просто переделай не конечные узлы в каналы.

14 февр. 2018 г. 21:17 пользователь "vladitep" <notifications@github.com>
написал:

Устал я по английски. Окей, это твое детище и ты решаешь как его развивать,
но ты не можешь не знать что уже созданные стейты нельзя переделать в
обьекты и каналы, такого функционала нв брокере нет. Под новую админку надо
полностью с нуля переделывать структуру обьектов умного дома, это нихрена
себе изменение чтобы о нем так вскользь упоминать.
О том что новая админка может быть не совмеситима со структурой обьектов
сисетмы надо писать огромными буквами в трех местах, а не щипцами из тебя
это вытягивать. И уж тем более такую админку в продакшн с заменой старой
выкатывать нельзя, это просто неуважение ко всей твоей армии юзеров,
тестеров и разрабов.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/ioBroker/ioBroker.admin/issues/196#issuecomment-365732025>,
or mute the thread

**Comment by GermanBluefox** [comment]
I must confess there is no need to create extra channels. Just one rule:
states may not have sub-states.

14 февр. 2018 г. 20:35 пользователь "Ingo Fischer" <notifications@github.com>
написал:

**Comment by vladitep** [comment]
окей. Я спрошу еще раз. То что админ и редактор скриптов показывает одно а виз редактор другое - так и должно быть? У меня это проявляется сплошь и рядом, на любых объектах, на конечных стейтах без сабстейтов. 
Это не является багом? 
Так и должно быть?
