### ISSUE TITLE
[bug]: Ford adapter doesn't update values. - Failed to force update - Error: getaddrinfo ENOTFOUND usapi.cv.ford.com

### ISSUE THREAD

**Issue by MartinRamsch** [ioBroker/ioBroker.admin#2219]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

The Ford adapter doesn't update its data points anymore.
Only timestamps and data in sections ford.0.XXXXXXXXX.capabilities and ford.0.XXXXXXXXX.general are updated.
Timestamps and data in all other sections are frozen.

Ford restart shows erros:
error https://usapi.cv.ford.com/api/vehicles/v2/WF0FXXWPMHNA73824/status
error Error: getaddrinfo ENOTFOUND usapi.cv.ford.com
error Failed to force update

### To Reproduce

1. restart Ford adapter

### Expected behavior

The ford adapter should update its data points

### Screenshots & Logfiles

ford.0 | 2023-11-14 18:55:03.557 | error | https://usapi.cv.ford.com/api/vehicles/v2/WF0FXXWPMHNA73824/status
ford.0 | 2023-11-14 18:55:03.537 | error | Error: getaddrinfo ENOTFOUND usapi.cv.ford.com
ford.0 | 2023-11-14 18:55:03.537 | error | Failed to force update

### Adapter version

Ford 0,0,14

### js-controller version

4.0.21

### Node version

v14.21.3

### Operating system

Raspbian GNU/Linux 10 (buster

**Comment by mcm1957** [comment]
@MartinRamsch 

**This is for sure no issue with admin**

Please create a issue at adapter repo (https://github.com/TA2k/ioBroker.ford) or a discussion at forum (forum.iobroker.net) if the problem still exists with the current release.

**Additionally you should update your system**.
current adapter version is 0.2.0 (and not 0.0.14)
js-controller 4.0.21 is outdated (last 4.0.x was 4.0.24), current version is 5.0.16
node 14 is outdated since a long time, node 16 is EOL in the meantime too. You should update to node 18 minimum.
Debian 10 is also ruther old and you should consider updating.

**Comment by Apollon77** [comment]
Ps: ENOTFOUND means that the dns lookup do not work. So maybe also check that.

**Comment by MartinRamsch** [comment]
gg

> @MartinRamsch
> 
> **This is for sure no issue with admin**
> 
> Please create a issue at adapter repo (https://github.com/TA2k/ioBroker.ford) or a discussion at forum (forum.iobroker.net) if the problem still exists with the current release.
> 
> **Additionally you should update your system**. current adapter version is 0.2.0 (and not 0.0.14) js-controller 4.0.21 is outdated (last 4.0.x was 4.0.24), current version is 5.0.16 node 14 is outdated since a long time, node 16 is EOL in the meantime too. You should update to node 18 minimum. Debian 10 is also ruther old and you should consider updating.

Even afer reinstalling the Ford adapter only release 0.0.14 is shown.

**Comment by mcm1957** [comment]
Most likely you did a github intsallation and missed some steps required when installing from github.

In addtion adapter release 2.0.0 uses adapter-core which in turn requires node 16 to install an woirk properly. Did you update node and js-controller?

I suggest to create a topic at forum (forum.iobroker.net) if you need any more help as this is no admin issue.

**Comment by MartinRamsch** [comment]
I upgraded to node v18.17.1 and npm 9.6.7.
The issues still exists. Ford 0.0.14 is the maximum version available in iobroker adapter screen.

**Comment by ldittmar81** [comment]
@MartinRamsch der Fehler hat nichts mit dem Admin zu tun. Bitte eine Fehlermeldung in https://github.com/TA2k/ioBroker.ford anlegen.

The error has nothing to do with the admin. Please create an error report at https://github.com/TA2k/ioBroker.ford.

**Comment by mcm1957** [comment]
@MartinRamsch 
The maintainer of ioBroker.ford did not update it adapter at the offizial stable repository since some time. It's his responsibility to request an update if a new release is stable and should be published.
See https://github.com/TA2k/ioBroker.ford/issues/22

Please contact him and / or create a issue at the adapter repository https://github.com/TA2k/ioBroker.ford/issues

**Comment by MartinRamsch** [comment]
Thanks for updating in iobroker.ford.
You recommended to update Debian. To which version? Could you pass a reference for teh update procedure?

**Comment by mcm1957** [comment]
> Thanks for updating in iobroker.ford. You recommended to update Debian. To which version? Could you pass a reference for teh update procedure?

Please take a look at our forum https://forum.iobroker.net. Shoudl have been discussed there. Or open a new topic at forum for such general qeuestions.
