### ISSUE TITLE
[bug]: Object browser with type filter never finishes loading

### ISSUE THREAD

**Issue by AlexanderSchulz-Siemens** [ioBroker/ioBroker.admin#2273]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When using the object browser `objectId` with a types filter, the browser opens but never finishes loading.

### To Reproduce

```
{
    "items": {
        "objectId": {
            "type": "objectId",
            "types": ["channel", "folder"],
            "sm": 12
        }
    }
}
```

### Expected behavior

Finishes loading and allows selection of the specified types, just like the object browser without type filter.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/95072420/df16bbbf-1538-4c08-a090-a97013a0b714)

### Adapter version

6.12.9

### js-controller version

5.0.17

### Node version

20.10.0

### Operating system

Windows 10

### Additional context

Tested with Chrome 120.0.6099.111

**Comment by foxriver76** [comment]
There is some weirdness in there, it seems like the JSON config component only accepts a single string here (singular should most likely be plural in the screenshot). 

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/b0a8c67f-eebb-49e0-b603-dee02134a839)

If you already provide an array it will be a nested array due to https://github.com/ioBroker/ioBroker.admin/blob/2d07a830012a9508d80fc1901d66b9aa3a01be3d/packages/jsonConfig/src/JsonConfigComponent/ConfigObjectId.jsx#L81

And all of this seems like, because `ObjectBrowser` only supports one type currently https://github.com/ioBroker/adapter-react-v5/blob/73a37320f7a7288120332839b0b0c4a6492f62bc/src/Components/ObjectBrowser.js#L2176-L2178

Unfortunately, the [schema sates different ](https://github.com/ioBroker/adapter-react-v5/blob/73a37320f7a7288120332839b0b0c4a6492f62bc/schemas/jsonConfig.json#L3989)and the plural `types` isn't really helpful here, I would have preferred something like `filterType` or similar. 

Soa ccording to the docs, `customFilter` will do the trick for you. However, we should fix the schema for this one.

**Comment by AlexanderSchulz-Siemens** [comment]
Yes, `"customFilter": "{type: ['channel', 'folder']}"` did the trick. However, my intention was not to select a state but rather a folder / channel. Is that possible?

**Comment by foxriver76** [comment]
It was not possible previously, Bluefox implemented something today https://github.com/ioBroker/ioBroker.admin/commit/5e8ca77e175715d81533d46bf9569131a2ed9b8d, I will let you know as soon as I have any news on usage.

**Comment by foxriver76** [comment]
Okay just tested and your example should work now as provided in your first post with 6.13.5
