### ISSUE TITLE
[enhancement]: Back from Github Version to latest Version not possible directly.

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.admin#2279]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

no

### Description

I installes the github Version of an adapter. For example Version 0.4.2
When I want to go back to the latest. Actual it is V0.0.67 its not possible directly:
![image](https://github.com/ioBroker/ioBroker.admin/assets/50423935/4cfcf62d-0f0c-4a89-b986-e72979037da3)
![image](https://github.com/ioBroker/ioBroker.admin/assets/50423935/38b357f8-188e-4d06-84a5-661fc7d2c68d)

There should be the option to install the latest version with this button:
![image](https://github.com/ioBroker/ioBroker.admin/assets/50423935/0abbf8af-f1ce-4ed0-8813-a1d3c65b2ddf)

**Comment by mcm1957** [comment]
LATEST Version is 0.5.1
STABLE version is 0.0.67 - it's up to the maintainer of the adapter to request an update at stable repository. Please raise a issue at adapter repository eventually.

Versions below 0.1.0 have been removed from current io-package.json by maintainer.

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/5b2c2b0c-f851-47d4-8461-fc0f2d1d3b13)

**Comment by unstressable** [comment]
Sorry I meant stable, not latest.

there is no possibility to install the newest stable version throught then menu i screenshotted.
Only one version earlier.

**Comment by foxriver76** [comment]
Admin simply uses the information from the `system.repository` object, which is the cached repository. And this is build up from `io-package.json` of the adapter, so the question would be why 0.0.60 was there in the news and `0.0.67` not. Basically it should be there, else we would have no news to display when installing the stable version.

I checked with multiple other adapters and was able to reinstall the current stable version. So probably the news were not added to the adapter for this version.

**Comment by mcm1957** [comment]
I think this a special problem caused by the maintainer of adapter vw-connect. The stable release of this adapter is very outdated and the current  io-package infoamtion for this adapter does no longe contain any information abaout 0.0.67 release. The missing information cannot be guessed by admin.

I would suggest to open a issue at the adapter repository ans ask the dev to update the stable release.

If you encounter the same problem with any adapgter which is maintained normally please provide infomation aboit this adapter.
