### ISSUE TITLE
[bug]: Status Tab of ACME-Adapter not working with Admin 7.4.3 

### ISSUE THREAD

**Issue by SVallant** [ioBroker/ioBroker.admin#2848]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

"Tab" Status of ACME-adapter show only "moving" blue line, in previous version certs were listed. 

### To Reproduce

1. install iobroker.acme
2. Go to instances => ACME => Settings => Status
3. See error

### Expected behavior

Tab shows a list of certs

### Screenshots & Logfiles

![393007310-06fcc496-ac12-42a4-b633-486344fdcc81](https://github.com/user-attachments/assets/d269ace2-c7d6-4913-a63a-582810479a10)

### Adapter version

7.3.4

### js-controller version

7.0.4

### Node version

20.18.1

### Operating system

Ubuntu LTS 24.04

**Comment by Feuer-sturm** [comment]
@SVallant Since 06.12.2024 the version 1.0.4 of acme is available (Changelog "Corrected error with admin 7.4.3"). Please check if with this version the behavior changes.

**Comment by mcm1957** [comment]
@Feuer-sturm 
- Svallant initially opened https://github.com/iobroker-community-adapters/ioBroker.acme/issues/149
- Bluefox noted in regard to this issue, that the problem is an admin issue. So this (#2848) has been created.
- Bluefox then created a ne acme (!) release (1.0.4)
- acme 1.0.4 does changes the problem but dies not solve ist. See https://github.com/iobroker-community-adapters/ioBroker.acme/issues/149

So the problem should be analyzed by @GermanBluefox as it is related to react / admin anyway

**Comment by SVallant** [comment]
solved with 7.4.4 thank you
