### ISSUE TITLE
object state  "from"

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#540]
current behavior :
if I set a value in custom the admin interface, the "from" state at the object is not update with the admin instance.

expected behavior :
value "from" is update" with admin.>instancename<

How to repoduce :

- take source analytic as example
- change the setting at the state (equal to influxes or data loggers)
- data is written in the object within "custom"
- value "from" is not updated

why is this an issue : We can't identify if an object change is cause by the source admin.>instance<

**Comment by Apollon77** [comment]
Admin needs to make sure to clear out "from" field (and also ts field?) when reading the object in order to change it ... because if setObject is called with .from/.ts set these values are preserved

**Comment by DutchmanNL** [comment]
Hmm clean of set, we Must ensure the from is updated with admin Instanzen to see the source of initiated change

**Comment by GermanBluefox** [comment]
There are two "from"s: for object and for state. 
Object's from will be changed only if the content of object changed.

**Comment by Apollon77** [comment]
here it is all about object

**Comment by Apollon77** [comment]
Background: Admin often user getObejcts - change setObject behaviour.
But a setObject with a provided from will not be altered by the js-controller logic, so admin needs to remove from (and pot also ts fielda) from the object  before calling "setObject" so that it is clearly visible that the setObject was done by admin. ALternatively admin could overwrite from with his own namespace

**Comment by GermanBluefox** [comment]
Done
