### ISSUE TITLE
Display of adapter icons are dependent on network connection to GitHub.com

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.admin#74]
With GitHub being offline yesterday I recognised that within iobroker.admin the display of icons on the main page didn't work. After some short investigation I recognised that the logos seem to be directly referenced from raw.githubusercontent.com which was also unavailable at the time I loaded my iobroker admin page and thus the display failed. See here:

![screenshot_86](https://cloud.githubusercontent.com/assets/5887769/19620373/809ecfaa-987c-11e6-93e0-012a2324a1e0.png)
![screenshot_87](https://cloud.githubusercontent.com/assets/5887769/19620376/86a299ae-987c-11e6-8f04-52d0495d4379.png)

Interestingly the adapter icons on the "Instances" tab were shown correctly.

To me it seems to be valuable to bring up a request to remove all these kind of direct references to GitHub hosted content as
1. not all iobroker installations might have direct internet access.
2. the speed of loading the main iobroker.admin pages might get faster if the icons would be referenced locally only.

**Comment by foxriver76** [comment]
This is due to the fact, that "Instances" seems to use the "extIcon" attribute of io-package while "Adapters-Tab" uses just the "icon" attribute, which is a local path. Are there any pros on using the external icons in comparison to the usage of the local stored icons? Because I don't see any -- so should be easy to switch.

**Comment by Apollon77** [comment]
Instances can use local icons because these plugins are all installed locally. 

Adapter screen shows the whole Adapter List
And most of them will not be installed on your host ...

**Comment by foxriver76** [comment]
Of course, thanks. Was too late to think clearly. So only thing would be to use the icon path when an adapter is installed. Non installed adapters won’t be shown (or at least can’t be installed and read me also not accessible when once updated adapters while there was a connection) in an offline setup.

**Comment by Apollon77** [comment]
But does this really solve the issue?! Then it is even more strange because some icons are shown, most not.
I think the idea would be to find a way to catch all icons, resize them as needed and put them together in a sprite file or such which is also loaded with a repo update

**Comment by foxriver76** [comment]
Sounds good, on the other hand we would have to do this procedure every time, when the cli with "iobroker update" is called, because icons can change too. And when we address this issue, maybe it would also be an idea to deactivate the readme and the add button of adapters which are not installed -- maybe with an information (e. g. by hovering over the buttons) that says, that the host has no internet connection -- otherwise they are not functional.

**Comment by Apollon77** [comment]
No we need to do that once on the server side where repo is collected at all and then on update only the new file needs to be loaded

**Comment by wendy2702** [comment]
@foxriver76 @Apollon77 : has this been „fixed“ or changed?

**Comment by foxriver76** [comment]
I don't think so.. but admin is out of my scope most of the time

**Comment by wendy2702** [comment]
OK.

I will do a retest if i have access to my system.

**Comment by Apollon77** [comment]
It is still the case

**Comment by GermanBluefox** [comment]
Admin5 should do it better
