### ISSUE TITLE
Anzeige RAM frei zeigt falschen Wert an

### ISSUE THREAD

**Issue by froststrm** [ioBroker/ioBroker.admin#76]
In der Statuszeile der Instanzen-Ansicht wird folgendes gezeigt (beispielhaft):

Insgesamt RAM verbraucht: 169 MB / Frei: 84 MB (4%) [Host: cubietruck - 3 Prozesse]

Allerdings ist die RAM-Frei-Information falsch. Es sollte dort meiner Meinung nach nicht nur der unbenutzte RAM berücksichtigt werden, sondern auch der vom Cache benutzte RAM, weil dieser ja bei Bedarf auch Anwendungen zur Verfügung steht (=available)!

Siehe auch: http://www.linuxatemyram.com/

**Comment by fjjat** [comment]
die Werte (auch RAM verbraucht) sind für mich nicht ganz nachvollziehbar

Insgesamt RAM verbraucht: 421 MB / Frei: 102 MB (11%) [Host: pi-CCU2 - 10 Prozesse]

$free -m
                   total       used       free     shared    buffers     cached 
Mem:           925        819        105          6           65            388
-/+ buffers/cache:    365        559
Swap:           99          0         99

Raspberry 3 - Jessie - Node v6.9.5

**Comment by GermanBluefox** [comment]
Für mich sind die auch nicht ganz nachvollziehbar, aber geben grobes Bild
über Verbrauch. Wenn du Lösung kennst bitte PullRequest.

Am 18.02.2017 08:47 schrieb "fjjat" <notifications@github.com>:

die Werte (auch RAM verbraucht) sind für mich nicht ganz nachvollziehbar

Insgesamt RAM verbraucht: 421 MB / Frei: 102 MB (11%) [Host: pi-CCU2 - 10
Prozesse]

$free -m
total used free shared buffers cached
Mem: 925 819 105 6 65 388
-/+ buffers/cache: 365 559
Swap: 99 0 99

Raspberry 3 - Jessie - Node v6.9.5

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ioBroker/ioBroker.admin/issues/76#issuecomment-280829329>,
or mute the thread
