### ISSUE TITLE
Admin 5 - hidden attribute ignored

### ISSUE THREAD

**Issue by Excodibur** [ioBroker/ioBroker.admin#809]
In Admin5, I can't get the [hidden attribute](https://github.com/ioBroker/ioBroker.admin/blob/f475d854bffd6089ad337b2584d8e279d11a98d7/src-rx/src/components/JsonConfigComponent/SCHEMA.md) to work in the code here: https://github.com/ioBroker/ioBroker.influxdb/pull/99/files#diff-05750c3138da2b61c537e66f43511bf18914f9e25e4fff2dde9e454f1f95b715

Depeding on choice taken in the select-field some input-fields should be hidden, while others should be visible.

Currently it seems like the `hidden` attribute is ignored (or the condition is perhaps resolved strangely), as all the fields are shown regardless of what is selected.

Am I doing something wrong, or could this be a bug?

**Versions:**  
 - Adapter version: 4.2.1
 - JS-Controller version: 3.3.1
 - Node version: 14.15.5
 - Operating system: WSL Ubuntu 20.04

**Comment by GermanBluefox** [comment]
How you can text jsonConfig with admin  4.2.1?

Some notices:
- `repeat` flag can be applied only to attribute with type "password". For `token` attribute with type text it is useless.
- please use type "sendTo" instead of "sendto"
- please add flag `noTranslation` for `dbversion` as 1.x must not be translated
- Add flag `"default": "2.x"` to `dbversion` (Works only from adin 5.0.13)

**Comment by Excodibur** [comment]
You are right, I mentioned the wrong admin release. I used 5.0.11 before.

Thanks to your suggested config-changes it seems to work now. Thank you!

Please close the issue.
