### ISSUE TITLE
Admin 5: Sentry Status not correct at 'system.adapter.x.0.plugins.sentry.enabled'

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#837]
**Describe the bug**  
Datapoint `system.adapter.x.0.plugins.sentry.enabled` should be false if you disable sentry over button at instance Tab.
And the other direction, set `system.adapter.x.0.plugins.sentry.enabled` to `false`,  sentry logo at instance tab show still active

**To Reproduce**  
1. disable sentry over button at instance Tab
2. `system.adapter.x.0.plugins.sentry.enabled` still `true`

1. set `system.adapter.x.0.plugins.sentry.enabled` to `false`
2. sentry logo at instance tab show still active

**Expected behavior**  
`system.adapter.x.0.plugins.sentry.enabled` should be `false`

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/6370451/117429011-e45f4900-af26-11eb-96bb-48d7e32ed37e.png)

![grafik](https://user-images.githubusercontent.com/6370451/117429078-f50fbf00-af26-11eb-82bf-a24d66fc8af5.png)

and other direction:
![grafik](https://user-images.githubusercontent.com/6370451/117429551-75362480-af27-11eb-8e1e-6567287169f2.png)
![grafik](https://user-images.githubusercontent.com/6370451/117429476-62bbeb00-af27-11eb-9316-3fa70b2c54c3.png)

**Versions:**  
 - Adapter version: 5.0.15
 - JS-Controller version: 3.2.16

**Comment by Apollon77** [comment]
@Scrounger hm ... I agree that the "is sentry activated" should take the "enabled" state also into account.

I need to check what happens to the flag on instance restart if you disable dataReporting (aka Sentry in admin) ... I would expect that the plugin is setting the flag to false then itself!

**Comment by Apollon77** [comment]
Hm ... I checked it and the state is not updated when sentry got disabled by other mechanisms (and in fact this can be "diag" file from host the instance runs on.

The current logic is kind of
* first check the state if it is disabled there-> disabled
* else check instance object common.disableDataReporting if it is disabled there-> disabled (Admin 5 change that field)
* else check host object common.disableDataReporting if it is disabled there-> disabled (unused kind of because noone sets that flag)
* else if syste.config object "common.diag" is "none" -> disabled

The state is not updated to false because else it would not be enabled again.

So, I'm sorry but to have the same for your adapter we would need to mimic that ... maybe something also for adapter-react to offer as a convenient message?

@AlCalzone ?

**Comment by Scrounger** [comment]
Is ok for me.
This is only a nice to have feature. I know there will be questions from the community why the state is not shown correct ;-)

**Comment by Feuer-sturm** [comment]
> I know there will be questions from the community why the state is not shown correct ;-)

And here is the discussion https://forum.iobroker.net/topic/46813/admin-v5-jetzt-im-stable/511

**Comment by Feuer-sturm** [comment]
@Apollon77 @AlCalzone Is this an issue which can be fixed?
