### ISSUE TITLE
Admin 5.0.15: update JS-Controller nicht möglich (3.3.7 zu 3.3.8)

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#844]
siehe https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/395?_=1620453781388

„buanet“-Docker-Container mit Admin v5.0.15
Per Consolenbefehl ist die Aktualisierung möglich

**Comment by Apollon77** [comment]
Ich weiss noch nicht mal was das für ein upgrade befehl ist  :-)

**Comment by GermanBluefox** [comment]
It was not yet implemented in 5.0.18

**Comment by Feuer-sturm** [comment]
Admin 5.0.20
js-controller 3.3.7

I made a downgrade to js-controller 3.3.7 and it seems to work :-)

After this I opened the instructions for updatig js-controller. Currently it looks like this:
![Animation2](https://user-images.githubusercontent.com/25422320/117880105-01d63f00-b2a8-11eb-87a4-65704762d3b4.gif)


Here the translation is not finished yet:
![grafik](https://user-images.githubusercontent.com/25422320/117880724-b8d2ba80-b2a8-11eb-9e0a-45a1c1999903.png)

A question to this screen:
![grafik](https://user-images.githubusercontent.com/25422320/117880907-eb7cb300-b2a8-11eb-951a-907777a58a1c.png)

- How does the user know if he used the "new installation process" or if iobroker was installed manually. Perhaps add a link to the "new installer" so that the user can remember.

**Comment by Apollon77** [comment]
Yes new installer means the curl shell script

@Feuer-sturm would you up for providing a proposal as PR here https://github.com/ioBroker/ioBroker.docs/blob/master/admin/en/controller-upgrade.md and maybe in german in https://github.com/ioBroker/ioBroker.docs/blob/master/admin/de/controller-upgrade.md

What would you change? Go to the pages, klick the pencil top right, edit and propose as change and click "create PR"

The text comes from there :-)

**Comment by Feuer-sturm** [comment]
@Apollon77 ok, I will think about it and make a proposal.

**Comment by ice987987** [comment]
could you also add the proposed procedure for updating iobroker running with the [Docker Image](https://hub.docker.com/r/buanet/iobroker/)?

**Comment by Apollon77** [comment]
@ice987987 Honestly I do not know the "proposed procedure" ... But Happy to take a PR in above docs repo

**Comment by Feuer-sturm** [comment]
Pull request was accepted. I translated it into english as well https://github.com/ioBroker/ioBroker.docs/pull/314
