### ISSUE TITLE
Check devices and rooms icons

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.admin#975]
Please find new icons only on https://www.flaticon.com/

Devices:
![image](https://user-images.githubusercontent.com/4582016/120616619-ac7def80-c459-11eb-8771-5784299c18d6.png)

Rooms:
![image](https://user-images.githubusercontent.com/4582016/120616672-b4d62a80-c459-11eb-8d70-dd6de9cf8be0.png)

**Comment by Garfonso** [comment]
Suggestions:

Devices: 
1. Update Name "Luster"  to more common name "Kronleuchter"
2. Markisen has wrong icon, use https://www.flaticon.com/de/premium-icon/markise_3275229 or https://www.flaticon.com/de/kostenloses-icon/terrasse_3713138 or https://www.flaticon.com/de/kostenloses-icon/terrasse_3713527 or similar
3. Change Icon for Rasenmäher to depict lawn mower robot, like https://www.flaticon.com/de/kostenloses-icon/rasenmaher_3239215

Rooms:
1. I don't get what "Rückwand" should be? Back of a TV thingie?
2. From Wikipedia "Speis" can mean "Speisekammer" https://de.m.wikipedia.org/wiki/Speisekammer if that is what is meant, I'd write Speisekammer and the icon must be replaced with something else, like https://www.flaticon.com/de/kostenloses-icon/regale_2317084
3. There is a duplicate for "Treppe"
4. Rename "Werkstätte" to more common "Werkstatt"
5. "Windfang" needs a different icon. From Wikipedia it seems to be a very small room that is only there in order to have two doors https://de.m.wikipedia.org/wiki/Windfang_(Architektur)  I did not find a suitable icon. Maybe use the same as "Eingang"? Or a simple door https://www.flaticon.com/free-icon/door_605851

**Comment by Feuer-sturm** [comment]
Devices:
- Printer: https://www.flaticon.com/free-icon/print_4305625?term=printer&page=1&position=14&page=1&position=14&related_id=4305625&origin=search
- "Rechner" is duplicate
- Sprinkler: https://www.flaticon.com/premium-icon/sprinklers_4070347?term=sprinkler&page=1&position=13&page=1&position=13&related_id=4070347&origin=search and https://www.flaticon.com/free-icon/sprinkler_3239163?term=sprinkler&related_id=3239163
- smoke detector: https://www.flaticon.com/free-icon/smoke-detector_2752063?term=smoke%20alarm&page=1&position=17&page=1&position=17&related_id=2752063&origin=search or a similar one

**Comment by Videonisse** [comment]
Suggestions

Devices:

1. The names of the Devices should be uniform and either be in the singular or in the plural. Currently they both types are used, for example Schloss and Steckdosen. I suggest only singular is used.
2. Change Temperatur-Sensoren to https://www.flaticon.com/free-icon/thermometer_481474 or similar.

Questions:

1. What is the "Drücker"? Should it be a Door Lock?
2. If there is different icons for the same device type, would it not be better to just name them xx 1, xx 2 etc? For example: Beleuchtung = Licht 1, Stehlampe = Licht 2, Tischlampe = Licht 3, Deckenspot = Licht 4, Led Leiste = Licht 5, Wandlampe = Licht 6 etc. Or how should they be sorted in the GUI when the user shall select which one to use?

**Comment by santa81** [comment]
@GermanBluefox 
Als ich meine Räume und Funktionen angelegt hatte, gab es noch nicjt so viele zur Vorauswahl, wäre es theoretisch möglich die icons auf einfache Art meinen jetzigen Namen auch zuzuordnen?
Also ohne mir diese manuell herunterzuladen und dann erneut unter bearbeiten hochzuladen.

**Comment by GermanBluefox** [comment]
> 2\. If there is different icons for the same device type, would it not be better to just name them xx 1, xx 2 etc? For example: Beleuchtung = Licht 1, Stehlampe = Licht 2, Tischlampe = Licht 3, Deckenspot = Licht 4, Led Leiste = Licht 5, Wandlampe = Licht 6 etc. Or how should they be sorted in the GUI when the user shall select which one to use?

No. The Idea is to use these names for Alexa/Google control. I don't think it will be pleaser to say: "Schalte Licht 3 an" instead of "Schalte Tischlampe an".

**Comment by GermanBluefox** [comment]
Thank you for inputs!
Here is the new status: 
![image](https://user-images.githubusercontent.com/4582016/121066333-0cfa8d00-c7ca-11eb-8d7a-28945d7237ca.png)

![image](https://user-images.githubusercontent.com/4582016/121066375-18e64f00-c7ca-11eb-8466-66359ca53328.png)


The question: "is something missing? " is still open.
